global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['localhost:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['localhost:8428']
  - job_name: 'maintemplatev2'
    scheme: 'https'
    static_configs:
      - targets: ['localhost:8080']
