env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - `-s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`
    flags:
      - -a
      - -tags netgo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    id: booty
    main: ./main.go
    binary: booty

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
checksum:
  name_template: 'checksums.txt'
